services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: isuperhero
      POSTGRES_PASSWORD: password
      POSTGRES_DB: isuperhero_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
